import React from 'react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  BarChart,
  Bell,
  BookOpen,
  Briefcase,
  Building,
  Calendar,
  Camera,
  ChartLine,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Columns,
  Columns2,
  Columns3,
  Columns4,
  Copy,
  Crown,
  Database,
  Download,
  Edit,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileText,
  Filter,
  Flag,
  Folder,
  Globe,
  Grid3X3,
  GripVertical,
  Hash,
  Heart,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link,
  List,
  Loader,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Network,
  Package,
  Pause,
  PenTool,
  Phone,
  Play,
  Plus,
  PlusCircle,
  PoundSterling,
  Power,
  Printer,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  Sliders,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  Ticket,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  Video,
  Volume2,
  Wifi,
  X,
  XCircle,
  Zap,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';

export const iconRegistry = {
  activity: Activity,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  archive: Archive,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  award: Award,
  badgeCheck: BadgeCheck,
  barChart: BarChart,
  bell: Bell,
  bookOpen: BookOpen,
  briefcase: Briefcase,
  building: Building,
  calendar: Calendar,
  camera: Camera,
  chartLine: ChartLine,
  check: Check,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  columns: Columns,
  columns2: Columns2,
  columns3: Columns3,
  columns4: Columns4,
  copy: Copy,
  crown: Crown,
  database: Database,
  download: Download,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  fileCheck: FileCheck,
  fileText: FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  globe: Globe,
  grid: Grid3X3,
  gripVertical: GripVertical,
  hash: Hash,
  heart: Heart,
  helpCircle: HelpCircle,
  history: History,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: Key,
  layers: Layers,
  layoutDashboard: LayoutDashboard,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  loader: Loader,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  map: Map,
  mapPin: MapPin,
  menu: Menu,
  messageCircle: MessageCircle,
  minus: Minus,
  monitor: Monitor,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  move: Move,
  music: Music,
  network: Network,
  package: Package,
  pause: Pause,
  penTool: PenTool,
  phone: Phone,
  play: Play,
  plus: Plus,
  plusCircle: PlusCircle,
  poundSterling: PoundSterling,
  power: Power,
  printer: Printer,
  refreshCw: RefreshCw,
  rocket: Rocket,
  save: Save,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share,
  shield: Shield,
  shieldCheck: ShieldCheck,
  sliders: Sliders,
  slidersHorizontal: SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  ticket: Ticket,
  trash: Trash,
  trash2: Trash2,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  upload: Upload,
  user: User,
  userCheck: UserCheck,
  userCog: UserCog,
  userMinus: UserMinus,
  userPlus: UserPlus,
  users: Users,
  video: Video,
  volume2: Volume2,
  wifi: Wifi,
  x: X,
  xCircle: XCircle,
  zap: Zap,
} as const;

const iconAliases = {
  logout: 'logOut',
  add: 'plus',
  delete: 'trash',
  remove: 'trash',
  close: 'x',
  closeX: 'x',
  cancel: 'x',
  config: 'settings',
  profile: 'user',
  avatar: 'user',
  account: 'user',
  email: 'mail',
  message: 'messageCircle',
  chat: 'messageCircle',
  notification: 'bell',
  notifications: 'bell',
} as const satisfies Record<string, keyof typeof iconRegistry>;

export type IconName = keyof typeof iconRegistry | keyof typeof iconAliases;

export interface IconProps extends Omit<LucideProps, 'size'> {
  name: IconName;
  size?: number | string;
  className?: string;
  style?: React.CSSProperties;
}

export function getIconComponent(
  name: IconName
): React.ComponentType<LucideProps> | null {
  const directIcon = iconRegistry[name as keyof typeof iconRegistry];
  if (directIcon) return directIcon;

  const aliasedIcon = iconAliases[name as keyof typeof iconAliases];
  if (aliasedIcon) return iconRegistry[aliasedIcon];

  return null;
}

export function Icon({
  name,
  size = 24,
  className,
  style,
  ...props
}: IconProps): React.ReactElement {
  const directIcon = iconRegistry[name as keyof typeof iconRegistry];
  if (directIcon) {
    return React.createElement(directIcon, {
      size,
      className,
      style,
      ...props,
    });
  }

  const aliasKey = name as keyof typeof iconAliases;
  const aliasTarget = iconAliases[aliasKey];
  if (aliasTarget) {
    const aliasedIcon = iconRegistry[aliasTarget];
    if (aliasedIcon) {
      return React.createElement(aliasedIcon, {
        size,
        className,
        style,
        ...props,
      });
    }
  }

  console.error(
    `Failed to load icon: "${String(
      name
    )}" - Not found in registry or aliases. Try: "logOut", "plus", "settings", "user"`
  );
  return React.createElement(AlertTriangle, {
    size,
    className,
    style,
    color: 'red',
    ...props,
  });
}

export default Icon;
export { iconRegistry as appIcons };
export type { IconName as AppIconType };

export const AppIcon = Icon;
